image:
  repository: joplin/server
  tag: latest
  pullPolicy: IfNotPresent

env:
  APP_PORT: "22300"
  APP_BASE_URL: "https://joplin.my-domain.de"
  DB_CLIENT: "pg"
  POSTGRES_DATABASE: "joplin"
  POSTGRES_USER: "joplin"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: joplin-postgresql
  POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: joplin-postgresql
        key: password

service:
  type: ClusterIP
  port: 22300

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: joplin.my-domain.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: joplin-tls
      hosts:
        - joplin.my-domain.de

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

postgresql:
  enabled: true
  fullnameOverride: joplin-postgresql

  auth:
    database: joplin
    username: joplin

  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
    pullPolicy: IfNotPresent

  primary:
    persistence:
      enabled: true
      size: 8Gi

  global:
    imageRegistry: ""
    imagePullSecrets: []
    security:
      allowInsecureImages: true
