apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin-ingress
  namespace: joplin
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - notes.meinedomain.de
      secretName: joplin-tls
  rules:
    - host: notes.meinedomain.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: joplin-server
                port:
                  number: 22300
