image:
  repository: joplin/server
  tag: latest
  pullPolicy: IfNotPresent

env:
  APP_PORT: "22300"
  APP_BASE_URL: "https://notes.meinedomain.de"
  DB_CLIENT: "pg"
  POSTGRES_PASSWORD: "supergeheimespasswort"
  POSTGRES_DATABASE: "joplin"
  POSTGRES_USER: "joplin"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "joplin-db-postgresql.joplin.svc.cluster.local"

service:
  type: ClusterIP
  port: 22300

ingress:
  enabled: true
  className: "nginx" # oder "traefik" je nach Cluster
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: notes.meinedomain.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: joplin-tls
      hosts:
        - notes.meinedomain.de
