apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "joplin.fullname" . }}
  labels:
    app: {{ include "joplin.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "joplin.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "joplin.name" . }}
    spec:
      containers:
        - name: joplin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 22300
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

            - name: DB_CLIENT
              value: "pg"

            - name: POSTGRES_HOST
              value: "{{ include "joplin.fullname" . }}-postgresql"

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_DATABASE
              value: "{{ .Values.postgresql.auth.database }}"

            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.auth.username }}"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "joplin.fullname" . }}-postgresql"
                  key: postgres-password

          volumeMounts:
            - name: joplin-data
              mountPath: /home/joplin/data

      volumes:
        - name: joplin-data
          persistentVolumeClaim:
            claimName: "{{ include "joplin.fullname" . }}-data"
