apiVersion: v1
kind: Service
metadata:
  name: {{ include "joplin.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22300
  selector:
    app: {{ include "joplin.name" . }}
